config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :trips do
    resources :flights, only: %i[new create edit update destroy]
    resources :recommendations, only: [:index]
    resources :events, only: %i[new create edit update destroy]
    resources :hotels, only: %i[new create edit update destroy]
  end
  # resources :events, only: [:destroy]
  resources :user_trips, only: [:destroy]
  patch '/trips/:trip_id/events/:id/update_position', to: 'events#update_position', as: 'update_position'
  patch '/trips/:trip_id/events/:id/move_lists', to: 'events#move_lists', as: 'move_lists'
  get 'trips/:trip_id/invite', to: 'trips#invite', as: 'trip_invite'
  get '/trips/:trip_id/overview', to: 'trips#overview', as: 'trip_overview'
  post "/trips/:trip_id/overview/send_email", to: 'trips#send_email', as: 'send_email'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :user_trips, dependent: :destroy
  has_many :flights, dependent: :destroy
  has_many :hotels, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :users, through: :user_trips
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  require "kmeans-clusterer"

  def create
    @trip = Trip.new(trip_params)
    authorize @trip
    @trip.save
    redirect_to trip_recommendations_path(@trip)
  end

  def index
    @trips = policy_scope(Trip)
  end

  def invite
    @trip = Trip.find(params[:trip_id])
    authorize @trip
    unless UserTrip.where(user_id: current_user.id, trip_id: @trip.id).exists?
      UserTrip.create(user_id: current_user.id, trip_id: @trip.id)
    end
    redirect_to @trip
  end

  def show
    @trip = Trip.find(params[:id])
    authorize @trip
    @flights = @trip.flights
    @hotels = @trip.hotels
    @event = Event.new
    @flight = Flight.new
    @hotel = Hotel.new
    # get events for different sources
    @recommendations = Event.where(trip: @trip, source: 'google', selected: nil, start_time: nil)
    @self_created = Event.where(trip: @trip, source: 'self', start_time: nil)
    # filtering all events associated with the trip
    @events = @trip.events
    # geoclustering events and populating trip
    unless @trip.skip == true || @trip.generated == true
      @clusters = events_clustering(@events)
      generate_event_start_time(event_generation)
    end
    # gathering the events for the show page
    @events = @events.where.not(start_time: nil).order(:start_time, :position)
    @all_dates = (@trip.start_date.to_date..@trip.end_date.to_date).to_a
    @events_by_day = {}
    @all_dates.each do |date|
      events_that_day = @events.select { |e| e.start_time.to_date == date }.sort_by { |e| e.position }
      @events_by_day[date] = events_that_day
    end

    @categories = search_categories

    # events for the first day - will show as default on the trip show page
    @first_day_events = @events_by_day.first[1]
    @first_day_date = @events_by_day.first[0]

    # when a tab is clicked, it will send a request to get the day's events
    if params[:date].present?
      @events = @events_by_day[params[:date].to_date]
      @date = params[:date].to_date
    end

    respond_to do |format|
      format.html
      # this renders the tab info when you click on a specific day
      format.text { render partial: 'trips/events', locals: { events: @events, date: @date, trip: @trip, flights: @flights, hotels: @hotels }, formats: [:html] }
    end
  end

  def overview
    @trip = Trip.find(params[:trip_id])
    authorize @trip
    @flights = @trip.flights
    @hotels = @trip.hotels
    @user = @trip.users.first
    # select the events selected by user
    @events = @trip.events.where.not(start_time: nil).order(:start_time, :position)

    @all_dates = (@trip.start_date.to_date..@trip.end_date.to_date).to_a
    @events_by_day = {}
    @all_dates.each do |date|
      events_that_day = @events.select { |e| e.start_time.to_date == date }.sort_by { |e| e.position }
      @events_by_day[date] = events_that_day
    end
    if @events.last
      @highest_position = @events.last.position
    else
      @highest_position = 1
    end
    @categories = search_categories
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: @trip.destination,
               template: "trips/trip",
               formats: [:html],
               disposition: :attachment,
               layout: 'pdf'
      end
    end
  end

  def update
    @trip = Trip.find(params[:id])
    authorize @trip
    @trip.update(trip_params)
    redirect_to @trip
  end

  def send_email
    @trip = Trip.find(params[:trip_id])
    authorize @trip
    @user = current_user
    UserMailer.send_email(@trip, @user).deliver_now
  end

  private

  def trip_params
    params.require(:trip).permit(:destination, :start_date, :end_date, :latitude, :longitude, :skip)
  end

  def events_clustering(events)
    coords = []
    clustered_events = []
    events.each do |event|
      coords.append([event.latitude, event.longitude])
      clustered_events.append(event.id)
    end
    # k represents the number of clusters, and is based on the length of the trip
    k = (@trip.end_date.to_datetime.to_i - @trip.start_date.to_datetime.to_i + 86_400) / 86_400
    kmeans = KMeansClusterer.run k, coords, labels: clustered_events, runs: 3
    clusters = []
    kmeans.clusters.each do |cluster|
      clusters.append(cluster.points.map(&:label))
    end
    clusters
  end

  def event_generation
    @events.each do |event|
      range = @events.length
      event.position = rand(range)
    end
    @week_events = []
    selected_events = @events.where(selected: true).pluck(:id)
    unselected_events = @events.where(selected: nil).pluck(:id)
    number_of_day_events = 6 # Change number of events per day here
    cluster_number = 0
    while cluster_number < @clusters.length
      @day_events = []
      cluster = @clusters[cluster_number].shuffle
      if cluster.intersection(selected_events) # If user has selected any event belonging to the cluster.
        cluster.intersection(selected_events).each { |event_id| @day_events.append(event_id) if @day_events.length < number_of_day_events } # Inserting events selected by user first
      end
      cluster.intersection(unselected_events).each { |event_id| @day_events.append(event_id) if @day_events.length < number_of_day_events } # Filling up the gaps with events that were not selected.
      @week_events.append(@day_events) # Append the day's events to the week.
      cluster_number += 1
    end
    @trip.update(generated: true)
    @week_events
  end

  def generate_event_start_time(week_events)
    # Clearing dates for any stray events.
    @trip.events.each { |event| event.update(start_time: nil) }
    # Inserting dates for each day's events.
    date = @trip.start_date.to_datetime
    week_events.each do |day|
      day.each do |event_id|
        event = Event.find(event_id)
        event.update(start_time: date)
      end
      date += 1
    end
  end

  def search_categories
    { shopping: ["book_store",
                 "electronics_store",
                 "clothing_store",
                 "shoe_store",
                 "furniture_store",
                 "jewelry_store",
                 "department_store",
                 "shopping_mall"],
      attraction: ["casino",
                   "library",
                   "movie_theater",
                   "bowling_alley",
                   "amusement_park",
                   "museum",
                   "zoo",
                   "park",
                   "art_gallery",
                   "tourist_attraction"],
      food: ["bar",
             "cafe",
             "bakery",
             "restaurant",
             "night_club"] }
  end
end

app/views/trips/_event.html.erb
<% if event.category == nil %>
  <% bg_color = "var(--orange)" %>
<% elsif @categories[:shopping].any? { |type| event.category.include?(type)} %>
  <% bg_color = "var(--lightgreen)" %>
<% elsif @categories[:food].any? { |type| event.category.include?(type)} %>
  <% bg_color = "var(--pink)" %>
<% else %>
  <% bg_color = "var(--lightblue)" %>
<% end %>

<li class="event handle"
  data-index="<%= index %>"
  data-latitude="<%= event.latitude%>"
  data-longitude="<%= event.longitude %>"
  data-position="<%= event.position %>"
  data-place-id= "<%= event.source_id %>"
  data-sortable-update-url="<%= update_position_path(event.trip_id, event) %>"
  data-sortable-move-url="<%= move_lists_path(event.trip_id, event) %>"
>

  <div class="event-details" data-controller="edit-event" data-maps-target="event" data-directions-target="event" data-toggle-target="event" data-index=<%= index %> style="border: 3px solid <%= bg_color %>; background-color: <%= bg_color %>">
    <div class="position" style="text-align: right" data-sortable-target="position"><h3><%= index + 1 %></h3></div>
    <div class="event-inner-card" data-edit-event-target="card">
      <%= render "trips/event_details", event: event, trip: trip %>
    </div>

  <div class="event-directions" data-directions-target="directions">
    <div class="arrow" data-directions-target="arrow"></div>
    <div data-directions-target="driving" class="direction"></div>
    <div data-directions-target="transit" class="direction"></div>
    <div data-directions-target="walking" class="direction"></div>
  </div>
</li>

app/views/trips/_event_details.html.erb
<div class="event-photo-and-details">
  <div class="event-photo" style="background-image: url('<%= event.photo %>')"></div>
    <div class="basic-details">

      <div class="name-address">

        <p style="font-weight: bold" data-action="dblclick->edit-event#displayForm" data-edit-event-target="field">
          <% if event.category == nil %>
            <i class="fa-solid fa-user"></i>
          <% elsif @categories[:shopping].any? { |type| event.category.include?(type)} %>
            <i class="fa-solid fa-store"></i>
          <% elsif @categories[:food].any? { |type| event.category.include?(type)} %>
            <i class="fa-solid fa-utensils"></i>
          <% else %>
            <i class="fa-solid fa-mountain-city"></i>
          <% end %>
          &nbsp;
          <%= event.name %>
        </p>
        <%= simple_form_for [event.trip, event], data: {edit_event_target: "form", action: "submit->edit-event#update"}, html: {class: 'd-none'} do |f| %>
          <%= f.input :name, input_html: {class: "inline-edit"} %>
        <% end %>

        <p class="address" data-action="dblclick->edit-event#displayForm click->maps#singleEvent" data-edit-event-target="field" data-maps-target="address">
          <%= event.address %>
        </p>
        <%= simple_form_for [event.trip, event], data: {edit_event_target: "form", action: "submit->edit-event#update"}, html: {class: 'd-none'} do |f| %>
          <%= f.input :address, input_html: {class: "inline-edit"} %>
        <% end %>

      </div>

      <p class="info-toggle" data-action="click->toggle#toggleInfo" data-edit-event-target="sign">+</p>

    </div>

    <div class="coordinates d-none">
      <p data-maps-target="latitude"><%= event.latitude%></p>
      <p data-maps-target="longitude"><%= event.longitude %></p>
      <p data-maps-target="placeId"><%= event.source_id %></p>
    </div>

  </div>

  <div class="more-info d-none" data-toggle-target="info" data-edit-event-target="info">

    <div class="more-event-details">

      <p style="margin-right: 30px; margin-bottom: 10px;" data-action="dblclick->edit-event#displayForm" data-edit-event-target="field">
        <%= event.description %>
      </p>
      <%= simple_form_for [event.trip, event], data: {edit_event_target: "form", action: "submit->edit-event#update"}, html: {class: 'd-none'} do |f| %>
        <%= f.input :description, input_html: {class: "inline-edit"} %>
      <% end %>

      <% if event.website %>
        <p data-action="dblclick->edit-event#displayForm" data-edit-event-target="field"><strong><a href="<%= event.website %>" target="_blank">Website</a></strong></p>
        <%= simple_form_for [event.trip, event], data: {edit_event_target: "form", action: "submit->edit-event#update"}, html: {class: 'd-none'} do |f| %>
          <%= f.input :website, input_html: {class: "inline-edit"} %>
        <% end %>
      <% end %>

      <% if event.phone %>
        <p data-action="dblclick->edit-event#displayForm" data-edit-event-target="field">
          <strong>Phone:</strong> <%= event.phone %>
        </p>
        <%= simple_form_for [event.trip, event], data: {edit_event_target: "form", action: "submit->edit-event#update"}, html: {class: 'd-none'} do |f| %>
          <%= f.input :phone, input_html: {class: "inline-edit"}  %>
        <% end %>
      <% end %>

      <br>

      <p data-action="dblclick->edit-event#displayForm" data-edit-event-target="field" class="note">
        <% if event.note && event.note != "" %>
          <strong>Note:</strong> <%= event.note %>
        <% else %>
          Double click to add a note
        <% end %>
      </p>
      <%= simple_form_for [event.trip, event], data: {edit_event_target: "form", action: "submit->edit-event#update"}, html: {class: 'd-none'} do |f| %>
        <%= f.input :note, input_html: {class: "inline-edit"} %>
      <% end %>

    </div>
    <div class="modify-event" style="text-align: right">
      <%= link_to trip_event_path(trip, event), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
        <i class="fa-solid fa-trash-can"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/_recommendation_details.html.erb
    <div class="event-photo-and-details">

      <div class="event-photo" style="background-image: url('<%= event.photo %>')"></div>

      <div class="basic-details">

        <div class="name-address">

         <p style="font-weight: bold" data-action="dblclick->edit-event#displayForm" data-edit-event-target="field">
          <% if event.category == nil %>
            <i class="fa-solid fa-user"></i>
          <% elsif @categories[:shopping].any? { |type| event.category.include?(type)} %>
            <i class="fa-solid fa-store"></i>
          <% elsif @categories[:food].any? { |type| event.category.include?(type)} %>
            <i class="fa-solid fa-utensils"></i>
          <% else %>
            <i class="fa-solid fa-mountain-city"></i>
          <% end %>
          &nbsp;
          <%= event.name %>
        </p>
          <%= simple_form_for [event.trip, event], data: {edit_event_target: "form", action: "submit->edit-event#update"}, html: {class: 'd-none'} do |f| %>
            <%= f.input :name, input_html: {class: "inline-edit"} %>
          <% end %>

          <p class="address" data-action="dblclick->edit-event#displayForm click->maps#singleEvent" data-edit-event-target="field" data-maps-target="address">
            <%= event.address %>
          </p>
          <%= simple_form_for [event.trip, event], data: {edit_event_target: "form", action: "submit->edit-event#update"}, html: {class: 'd-none'} do |f| %>
            <%= f.input :address, input_html: {class: "inline-edit"} %>
          <% end %>

        </div>

        <p class="info-toggle" data-action="click->toggle#toggleInfo" data-edit-event-target="sign">+</p>

      </div>

    </div>

    <div class="more-info d-none" data-toggle-target="info" data-edit-event-target="info">

      <div class="more-event-details">

        <p style="margin-right: 30px; margin-bottom: 10px;" data-action="dblclick->edit-event#displayForm" data-edit-event-target="field">
          <%= event.description %>
        </p>
        <%= simple_form_for [event.trip, event], data: {edit_event_target: "form", action: "submit->edit-event#update"}, html: {class: 'd-none'} do |f| %>
          <%= f.input :description, input_html: {class: "inline-edit"} %>
        <% end %>

        <p data-action="dblclick->edit-event#displayForm" data-edit-event-target="field"><strong><a href="<%= event.website %>" target="_blank">Website</a></strong></p>
        <%= simple_form_for [event.trip, event], data: {edit_event_target: "form", action: "submit->edit-event#update"}, html: {class: 'd-none'} do |f| %>
          <%= f.input :website, input_html: {class: "inline-edit"} %>
        <% end %>

        <p data-action="dblclick->edit-event#displayForm" data-edit-event-target="field">
          <strong>Phone:</strong> <%= event.phone %>
        </p>
        <%= simple_form_for [event.trip, event], data: {edit_event_target: "form", action: "submit->edit-event#update"}, html: {class: 'd-none'} do |f| %>
          <%= f.input :phone, input_html: {class: "inline-edit"}  %>
        <% end %>

        <br>

        <p data-action="dblclick->edit-event#displayForm" data-edit-event-target="field" class="note">
          <% if event.note && event.note != "" %>
            <strong>Note:</strong> <%= event.note %>
          <% else %>
            Double click to add a note
          <% end %>
        </p>
        <%= simple_form_for [event.trip, event], data: {edit_event_target: "form", action: "submit->edit-event#update"}, html: {class: 'd-none'} do |f| %>
          <%= f.input :note, input_html: {class: "inline-edit"} %>
        <% end %>

      </div>

      <div class="modify-event" style="text-align: right">
        <%= link_to trip_event_path(trip, event), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-solid fa-trash-can"></i>
        <% end %>
      </div>

    </div>
  </div>

app/views/trips/index.html.erb
<div class="trip-index-background">
  <div class="container">
    <h1 style="font-weight: bold; text-align: center">Your Trips</h1>
    <div class="trips-box mt-5">
      <% @trips.each do |trip| %>
        <% user_trip = UserTrip.where(trip_id: trip.id, user_id: current_user.id).ids %>
        <div class="card-trip">
          <div class="card-cover" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://source.unsplash.com/random/?<%= trip.destination %>')">
            <%= link_to trip_path(trip.id) do %>
              <h1><%= trip.destination %></h1>
            <% end %>
          </div>
          <div class="card-trip-infos">
            <div class="trip-info">
              <h3><%= trip.start_date.strftime("%-d %B %Y") %> to <%= trip.end_date.strftime("%d %B %Y") %></h3>
              <div class="trip-links">
                <%= link_to "Go to trip", trip_path(trip.id) %>
                <%= link_to user_trip_path(user_trip), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/overview.html.erb
<% content_for :head do %>
  <meta name="turbo-visit-control" content="reload">
<% end %>

<div class="intro">
  <h2>Your <%= pluralize(@events_by_day.length, "days") %> in <strong><%= @trip.destination %></strong></h2>
  <div style="display: flex; align-items: center;">
    <%= link_to "See day-by-day view", trip_path(@trip) %>
    <%= link_to trip_overview_path(@trip, format: :pdf) do %>
      <i class="fa-solid fa-download" title="Download pdf"></i>
    <% end %>
    <%= form_with url: send_email_path(@trip), data: { controller: "send-email", send_email_target: "form", action: "submit->send-email#send"} do |f| %>
      <%= f.button style:"color:var(--green); border:none; background:none;" do %>
        <i class="fa-solid fa-paper-plane" title="Send to yourself"></i>
      <% end %>
    <% end %>
    <!-- Button trigger modal -->
      <button type="button" style="border: none; background: none;" data-bs-toggle="modal" data-bs-target="#myModel" id="shareBtn" data-bs-placement="top" title="Share with friends">
          <i class="fa-solid fa-share" style="margin-left: 5px"></i>
      </button>
      <!-- Modal -->
      <div class="modal fade" id="myModel" tabindex="-1" aria-labelledby="myModelLabel" aria-hidden="true">
          <div class="modal-dialog">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title" id="myModelLabel"><i class="fa-solid fa-meteor"></i> Copy the link below to share your trip!</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                      <%# <p>Copy link</p> %>
                      <div class="field d-flex align-items-center justify-content-between">
                          <div data-controller="clipboard" data-clipboard-success-content="Copied!">
                            <input style="width: 350px; padding: 5px; border-radius: 20px; color: grey; border: 1px solid grey; background-color: white;" type="text" value="<%= trip_invite_url(@trip) %>" data-clipboard-target="source" />
                            <button type="button" data-action="clipboard#copy" data-clipboard-target="button" class="flat-btn">Copy</button>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

<div class="container-fluid mt-3">
  <%= render "overview_events", trip: @trip, events_by_day: @events_by_day, all_dates: @all_dates, highest_position: @highest_position, flights: @flights, hotels: @hotels %>
</div>

app/views/trips/show.html.erb
<div>
  <% content_for :head do %>
    <meta name="turbo-visit-control" content="reload">
  <% end %>

  <div class="intro">
    <h2>Your <%= pluralize(@events_by_day.length, "days") %> in <strong><%= @trip.destination %></strong></h2>
    <div style="display: flex; align-items: center;">
      <%= link_to "See all days", trip_overview_path(@trip) %>
      <%= link_to trip_overview_path(@trip, format: :pdf) do %>
        <i class="fa-solid fa-download" title="Download pdf"></i>
      <% end %>
      <%= form_with url: send_email_path(@trip), data: { controller: "send-email", send_email_target: "form", action: "submit->send-email#send"} do |f| %>
        <%= f.button style:"color:var(--green); border:none; background:none;" do %>
          <i class="fa-solid fa-paper-plane" title="Send to yourself"></i>
        <% end %>
      <% end %>
      <!-- Button trigger modal -->
      <button type="button" style="border: none; background: none;" data-bs-toggle="modal" data-bs-target="#myModel" id="shareBtn" data-bs-placement="top" title="Share with friends">
          <i class="fa-solid fa-share" style="margin-left: 5px"></i>
      </button>
      <!-- Modal -->
      <div class="modal fade" id="myModel" tabindex="-1" aria-labelledby="myModelLabel" aria-hidden="true">
          <div class="modal-dialog">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title" id="myModelLabel"><i class="fa-solid fa-meteor"></i> Copy the link below to share your trip!</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                      <%# <p>Copy link</p> %>
                      <div class="field d-flex align-items-center justify-content-between">
                          <div data-controller="clipboard" data-clipboard-success-content="Copied!" style="">
                            <input style="width: 350px; padding: 5px; border-radius: 20px; color: grey; border: 1px solid grey; background-color: white;" type="text" value="<%= trip_invite_url(@trip) %>" data-clipboard-target="source" />
                            <button type="button" data-action="clipboard#copy" data-clipboard-target="button" class="flat-btn">Copy</button>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </div>
  </div>

  <div class="trip-overview" data-controller="maps toggle" data-action="update-events@window->maps#initMap">

    <div class="trip-content">

      <div class="tab-bar">
        <div class="tabs">
          <% @events_by_day.each_with_index do |date, index| %>
            <p class="tab <%= "tab-active" if index == 0 %>" data-toggle-target="tab" data-action='click->toggle#toggleTabs' data-toggle-url="<%= trip_path(@trip, date: @all_dates[index]) %>" data-index= "<%= index %>">
              Day <%= index + 1 %> |
              <%= @all_dates[index].strftime("%e %b") %>
            </p>
          <% end %>
        </div>
      </div>

      <%= render "events", events: @first_day_events, date: @first_day_date, trip: @trip, flights: @flights, hotels: @hotels %>
    </div>

    <div class="trip-tab">
      <label class="tab-label" for="show-map"><i class="fa-solid fa-map-location-dot"></i></label>
      <input type="radio" name="name" title="See map" checked="checked" id="show-map" />
      <div id="map" data-maps-target="map" data-action="google-maps-callback@window->maps#initMap"></div>

      <label class="tab-label" for="recommendations"><i class="fa-solid fa-layer-group"></i></label>
      <input type="radio" name="name" title="See recommendations" id="recommendations" />
      <div class="trip-tab-content trip-recommendation other-activities">
        <h2>Check out these other activities</h2>
        <ul
          data-controller="sortable"
          data-sortable-resource-name-value="event"
          data-sortable-handle-value=".handle"
          data-action="order-updated@window->sortable#updatePositions">
          <% @recommendations.each_with_index do |recommendation, index| %>
            <% if recommendation.category == nil %>
              <% bg_color = "var(--orange)" %>
            <% elsif @categories[:shopping].any? { |type| recommendation.category.include?(type)} %>
              <% bg_color = "var(--lightgreen)" %>
            <% elsif @categories[:food].any? { |type| recommendation.category.include?(type)} %>
              <% bg_color = "var(--pink)" %>
            <% else %>
              <% bg_color = "var(--lightblue)" %>
            <% end %>

            <li class="event handle"
              data-index="<%= index + 1 %>"
              data-latitude=<%= recommendation.latitude%>
              data-longitude=<%= recommendation.longitude %>
              data-position=<%= recommendation.position %>
              data-place-id=<%= recommendation.source_id %>
              data-sortable-update-url="<%= update_position_path(recommendation.trip_id, recommendation) %>"
              data-sortable-move-url="<%= move_lists_path(recommendation.trip_id, recommendation) %>">

              <div class="event-details" data-controller="edit-event" data-maps-target="event" data-directions-target="event" data-toggle-target="event" style="border: 3px solid <%= bg_color %>; background-color: <%= bg_color %>">
                <div class="position" style="text-align: right" data-sortable-target="position"><h3><%= index + 1 %></h3></div>
                <div class="event-inner-card" data-edit-event-target="card">
                  <%= render "trips/recommendation_details", event: recommendation, trip: @trip %>
                </div>

              <div class="event-directions" data-directions-target="directions">
                <div class="arrow" data-directions-target="arrow"></div>
                <div data-directions-target="driving" class="direction"></div>
                <div data-directions-target="transit" class="direction"></div>
                <div data-directions-target="walking" class="direction"></div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>

      <label class="tab-label" for="self-activities"><i class="fa-solid fa-user"></i></label>
      <input type="radio" name="name" title="See own activities" id="self-activities">
      <div class="trip-tab-content trip-recommendation list-own-activities">
        <h2>Your activities</h2>
        <ul
          data-controller="sortable"
          data-sortable-resource-name-value="event"
          data-sortable-handle-value=".handle"
          data-action="order-updated@window->sortable#updatePositions">
          <% @self_created.each_with_index do |sc, index| %>

            <li class="event handle"
              data-index="<%= index + 1 %>"
              data-latitude="<%= sc.latitude%>"
              data-longitude="<%= sc.longitude %>"
              data-position="<%= sc.position %>"
              data-place-id="<%= if sc.source_id then sc.source_id else nil end %>"
              data-sortable-update-url="<%= update_position_path(sc.trip_id, sc) %>"
              data-sortable-move-url="<%= move_lists_path(sc.trip_id, sc) %>">

              <div class="event-details" data-controller="edit-event" data-maps-target="event" data-directions-target="event" data-toggle-target="event" style="border: 3px solid var(--orange); background-color: var(--orange)">
                <div class="position" style="text-align: right" data-sortable-target="position"><h3><%= index + 1 %></h3></div>
                <div class="event-inner-card" data-edit-event-target="card">
                  <%= render "trips/event_details", event: sc, trip: @trip %>
                </div>

              <div class="event-directions" data-directions-target="directions">
                <div class="arrow" data-directions-target="arrow"></div>
                <div data-directions-target="driving" class="direction"></div>
                <div data-directions-target="transit" class="direction"></div>
                <div data-directions-target="walking" class="direction"></div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>

      <label class="tab-label" for="add-activities"><i class="fa-solid fa-plus"></i></label>
      <input type="radio" name="name" title="Create own activities" id="add-activities" />
      <div class="trip-tab-content create-own-activities">
        <h2>Create your own activities</h2>
        <div class="trip-tab-recommendation-container">
          <%= simple_form_for([@trip, @event]) do |f| %>
            <%= f.input :name %>
            <%= f.input :address, input_html: {data: {new_events_target: "address"}},
                                  wrapper_html: {data: {controller: "new-events",
                                                        new_events_api_key_value: ENV["GOOGLE_API_KEY"]}} %>
            <%= f.input :start_time, as: :string, label: "Date", input_html: { data: { controller: "flatpickr-events" }} %>
            <%= f.input :photo, as: :hidden, input_html: { value: "https://images.unsplash.com/photo-1569336415962-a4bd9f69cd83?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2831&q=80" } %>
            <%= f.input :source, as: :hidden, input_html: { value: "self" } %>
            <%= f.button :submit, class: "fat-btn" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>