config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :trips do
    resources :flights, only: %i[new create edit update destroy]
    resources :recommendations, only: [:index]
    resources :events, only: %i[new create edit update destroy]
    resources :hotels, only: %i[new create edit update destroy]
  end
  # resources :events, only: [:destroy]
  resources :user_trips, only: [:destroy]
  patch '/trips/:trip_id/events/:id/update_position', to: 'events#update_position', as: 'update_position'
  patch '/trips/:trip_id/events/:id/move_lists', to: 'events#move_lists', as: 'move_lists'
  get 'trips/:trip_id/invite', to: 'trips#invite', as: 'trip_invite'
  get '/trips/:trip_id/overview', to: 'trips#overview', as: 'trip_overview'
  post "/trips/:trip_id/overview/send_email", to: 'trips#send_email', as: 'send_email'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Pathfinder 2023.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, data: {turbo: false} do %>
      <h1><i class="fa-solid fa-meteor"></i> pathfinder</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link", data: {turbo: false} %>
          </li>
          <li class="nav-item">
            <%= link_to "Trips", trips_path , class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, class: "nav-link", data: {turbo_method: :delete}%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>